config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pomodoros#index'
  resources :users, only: [:show]
  resources :projects, only: [:create, :update, :destroy]
  resources :pomodoros, only: [:index, :create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pomodoro.rb
class Pomodoro < ApplicationRecord
  belongs_to :user
  belongs_to :project, optional: true
  accepts_nested_attributes_for :project
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :pomodoros
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_many :pomodoros
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/pomodoros_controller.rb
class PomodorosController < ApplicationController
  before_action :authenticate_user!
  # after_action :set_pomodoros

  def index
    @pomodoro = Pomodoro.new
    # PostgreSQLを使用したときには記述を変更する必要があるかもしれない
    @pomodoros_for_week = current_user.pomodoros.where('created_at > ?', 7.days.ago).where(status: 1).order(created_at: :desc).group_by{|pomodoro| pomodoro.created_at.strftime("%Y/%-m/%-d (%a)")}
  end

  def create
    @pomodoro = Pomodoro.create(pomodoro_params)
    @pomodoros_for_week = current_user.pomodoros.where('created_at > ?', 7.days.ago).where(status: 1).order(created_at: :desc).group_by{|pomodoro| pomodoro.created_at.strftime("%Y/%-m/%-d (%a)")}
  end

  def update
    @pomodoro = Pomodoro.find(params[:id])
    @pomodoro.update(status: params[:status])
    @pomodoro = Pomodoro.new
    @pomodoros_for_week = current_user.pomodoros.where('created_at > ?', 7.days.ago).where(status: 1).order(created_at: :desc).group_by{|pomodoro| pomodoro.created_at.strftime("%Y/%-m/%-d (%a)")}
  end

  def destroy
    @pomodoro = Pomodoro.find(params[:id])
    @pomodoro.destroy
    @pomodoro = Pomodoro.new
    @pomodoros_for_week = current_user.pomodoros.where('created_at > ?', 7.days.ago).where(status: 1).order(created_at: :desc).group_by{|pomodoro| pomodoro.created_at.strftime("%Y/%-m/%-d (%a)")}
  end

  private
  def pomodoro_params
    params.require(:pomodoro).permit(:title, :status, :project_id, :start_time, :end_time, :memo, project_attributes: [:title, :user_id, :total]).merge(user_id: current_user.id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    # @project = Project.new
    @projects = current_user.projects.where(status: 0).order('created_at DESC')
    # PostgreSQLを使用したときには記述を変更する必要があるかもしれない
    # @pomodoros = current_user.pomodoros.where('created_at > ?', 7.days.ago).order(created_at: :desc).group_by{|pomodoro| pomodoro.created_at.strftime("%F")}
  end

  def create
    # @project = Project.create(project_params)
    # @projects = current_user.projects.order('created_at DESC')
  end

  def edit
    # @project = Project.find(params[:id])
  end

  def destroy
    # @project = Project.find(params[:id])
    # @project.destroy
  end

  private
  def project_params
    params.require(:project).permit(:title, :status, :done, :total).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @projects = current_user.projects.where(status: 0).order('created_at DESC')
    @pomodoros = current_user.pomodoros.where(status: 1).order('created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pomodoros_helper.rb
module PomodorosHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pomodoro Tasks
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
  %body
    %nav.navbar.navbar-expand-lg.navbar-dark{:style => "background-color: #ea5549;"}
      = link_to "Pomodoro Tasks", root_path, class: "navbar-brand"
      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.ml-auto
          - if user_signed_in?
            %li.nav-item.active
              = link_to "#{current_user.name}", user_path(current_user.id), class: "nav-link"
            %li.nav-item.active
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link"
          - else
            %li.nav-item.active
              = link_to "ログイン", new_user_session_path, class: "nav-link"
            %li.nav-item.active
              = link_to "新規登録", new_user_registration_path, class: "nav-link"
    #wrapper{:style => "width: 65%; margin: 0 auto; padding-top: 30px;"}
      = yield

app/views/pomodoros/_edit_form.html.haml
= form_with model: pomodoro, id: 'new-pomodoro-form', class: 'new-pomodoro__form', method: :patch do |form|
  .new-pomodoro__form__display
    = form.text_field :title, class: "new-pomodoro__form__display__title form-control", placeholder: 'タスク名を入力してください'
    = form.fields_for 'project_attributes', pomodoro.project do |project|
      = project.text_field :title, class: "new-pomodoro__form__display__project", placeholder: 'プロジェクト名'
      = project.hidden_field :user_id, value: current_user.id
      = project.hidden_field :total, value: 0
    -# = form.collection_select :project_id, current_user.projects.where(status: 0), :id, :title, {prompt: "----"}, {class: "new-pomodoro__form__display__project"}
    %span#remaining-time.new-pomodoro__form__display__remaining-time
      25:00
    = form.hidden_field :end_time, value: DateTime.now
    = form.hidden_field :status, value: 1
    %span.new-pomodoro__form__display__buttons
      = button_tag type: 'submit', id: "pomodoro-stop", class: "new-pomodoro__form__display__buttons__stop btn" do
        %i.fa.fa-stop.fa-lg
      = link_to pomodoro_path(pomodoro.id), method: :delete, remote: true do
        = button_tag type: 'submit', id: "pomodoro-delete", class: "new-pomodoro__form__display__buttons__delete btn" do
          %i.fa.fa-trash.fa-2x
  .new-pomodoro__form__memo
    = form.label :memo, class: "new-pomodoro__form__memo__label"
    = form.text_area :memo, class: "new-pomodoro__form__memo__text-area form-control", rows: "4"

app/views/pomodoros/_new_form.html.haml
= form_with model: pomodoro, id: 'new-pomodoro-form', class: 'new-pomodoro__form' do |form|
  .new-pomodoro__form__display
    = form.text_field :title, class: "new-pomodoro__form__display__title form-control", placeholder: 'タスク名を入力してください'
    = form.fields_for 'project_attributes', pomodoro.project do |project|
      = project.text_field :title, class: "new-pomodoro__form__display__project", placeholder: 'プロジェクト名'
      = project.hidden_field :user_id, value: current_user.id
      = project.hidden_field :total, value: 0
    -# = form.collection_select(:project_id, current_user.projects.where(status: 0), :id, :title, {prompt: "----"}, {class: "new-pomodoro__form__display__project"})
    %span#remaining-time.new-pomodoro__form__display__remaining-time
      25:00
    = form.hidden_field :start_time, value: DateTime.now
    = form.hidden_field :status, value: 0
    %span.new-pomodoro__form__display__buttons
      = button_tag type: 'submit', id: "pomodoro-play", class: "new-pomodoro__form__display__buttons__submit btn" do
        %i.fa.fa-play.fa-lg

app/views/pomodoros/_pomodoros.html.haml
- pomodoros_for_week.each do |date, pomodoros|
  .pomodoros-for-week__each-day
    %p.pomodoros-for-week__each-day__date
      = date
    %ul.pomodoros-for-week__each-day__list.list-group
      - pomodoros.each do |pomodoro|
        %li.pomodoros-for-week__each-day__list__item.list-group-item
          %span.pomodoros-for-week__each-day__list__item__title
            = pomodoro.title
          %span.pomodoros-for-week__each-day__list__item__project.badge.badge-secondary
            = pomodoro.project.title
          %span.pomodoros-for-week__each-day__list__item__time
            = "#{pomodoro.start_time.strftime('%R')} - #{pomodoro.end_time.strftime('%R')}"

app/views/pomodoros/create.js.haml
:plain
  function zeroPadding(num) {
    return num < 10 ? '0' + num.toString() : num;
  }
  function countDown() {
    var remainingTime = $("#remaining-time").html();
    var remainingArray = remainingTime.split(':');
    var remainingSeconds = parseInt(remainingArray[0]) * 60 + parseInt(remainingArray[1]);
    remainingSeconds -= 1;
    if (remainingSeconds < 0) {
      clearInterval(timer);
      $("#remaining-time").html("終了");
      var url = $('#new-pomodoro-form').attr('action');
      var formData = new FormData();
      formData.append('end_time', '2019-09-08 12:20:55');
      formData.append('status', '1');
      $.ajax({
        url: url,
        type: "PATCH",
        data: formData,
        dataType: 'json',
        processData: false,
        contentType: false
      })
      .done(function(data){
        alert('投稿成功');
      })
      .fail(function(data){
        alert('投稿に失敗しました');
      })
    } else {
      $("#remaining-time").html(`${zeroPadding(Math.floor(remainingSeconds / 60))}:${zeroPadding(remainingSeconds % 60)}`);
    }
  }

  var timer = setInterval(countDown, 1000);

  $('#new-pomodoro').html("#{escape_javascript(render partial: 'pomodoros/edit_form', locals: { pomodoro: @pomodoro })}");
  $('#pomodoros-for-week').html("#{escape_javascript(render partial: 'pomodoros/pomodoros', locals: { pomodoros_for_week: @pomodoros_for_week })}")

app/views/pomodoros/destroy.js.haml
:plain
  clearInterval(timer);  
  $('#new-pomodoro').html("#{escape_javascript(render partial: 'pomodoros/new_form', locals: { pomodoro: @pomodoro })}");
  $('#pomodoros-for-week').html("#{escape_javascript(render partial: 'pomodoros/pomodoros', locals: { pomodoros_for_week: @pomodoros_for_week })}")

app/views/pomodoros/index.html.haml
-# #timer{:style => "width: 100%;height:280px;background-color:lightgray;text-align:center;padding-top:10px;border-radius:10px;"}
-#   %p.pomodoro-title{:style => "font-size:1.3em;margin-bottom:0"} ---
-#   %p#time{:style => "font-size:6.5em;letter-spacing:7px;margin-bottom:7px;"} 25:00
-#   .buttons{:style => "width:140px;height:48px;margin:0 auto;position:relative;"}
-#     %span#play{:style => "cursor:pointer;visibility:visible;position:absolute;top:0;left:0;"}= fa_icon "play 3x"
-#     %span#pause{:style => "cursor:pointer;visibility:hidden;position:absolute;top:0;left:0;"}= fa_icon "pause 3x"
-#     %span#stop{:style => "cursor:pointer;position:absolute;top:0;right:0;"}= fa_icon "stop 3x"
#new-pomodoro.new-pomodoro
  = render partial: 'pomodoros/new_form', locals: { pomodoro: @pomodoro }

#pomodoros-for-week.pomodoros-for-week
  = render partial: 'pomodoros/pomodoros', locals: { pomodoros_for_week: @pomodoros_for_week }

app/views/pomodoros/update.js.haml
:plain
  clearInterval(timer);
  $('#new-pomodoro').html("#{escape_javascript(render partial: 'pomodoros/new_form', locals: { pomodoro: @pomodoro })}");
  $('#pomodoros-for-week').html("#{escape_javascript(render partial: 'pomodoros/pomodoros', locals: { pomodoros_for_week: @pomodoros_for_week })}")

app/views/projects/_project.html.haml
/ <haml_silent> completion_rate = project.total == 0 ? 0 : (project.done / project.total.to_f * 100).round </haml_silent>
%li.list-group-item{:id => "project-#{project.id}", :style => "position:relative;"}
  / <haml_loud> link_to content_tag(:i, &#39;&#39;, class: &#39;fa fa-check fa-lg&#39;, id: &quot;project-#{project.id}-checkbox&quot;), &#39;&#39;, remote: true, style: &quot;margin-left: 8px;&quot; </haml_loud>
  %span.project-title= project.title
  / <span style="position:absolute;top:11px;right:120px;"><haml_loud> project.done </haml_loud> / <haml_loud> project.total </haml_loud></span>
  -# .progress{:style => "margin-top:8px;"}
  -#   .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => completion_rate, :role => "progressbar", :style => "width: #{completion_rate}%;"}
  -#     = completion_rate
  -#     \%
  %div{:style => "position:absolute;top:11px;right:24px;"}
    / <haml_loud> link_to content_tag(:i, &#39;&#39;, class: &#39;fa fa-edit fa-lg project-edit&#39;, id: &quot;project-#{project.id}-edit&quot;), edit_project_path(project.id), remote: true, style: &quot;margin-left: 8px;&quot; </haml_loud>
    %span.delete
      = link_to content_tag(:i, '', class: 'fa fa-trash fa-lg'), project_path(project.id), method: :delete, remote: true, style: "margin-left: 5px;"
    / <haml_loud> link_to content_tag(:i, &#39;&#39;, class: &#39;fa fa-save fa-lg&#39;), project_path(project.id), method: :patch, remote: true, style: &quot;margin-left: 5px;visibility:hidden;&quot; </haml_loud></span>

app/views/projects/create.js.haml
$("#tasks").append("#{escape_javascript(render partial: "tasks/task", locals: { task: @task })}");
$("#new_task")[0].reset();

app/views/projects/destroy.js.haml
var task = document.getElementById("task-#{@task.id}");
task.parentNode.removeChild(task);

app/views/projects/edit.js.haml
$("#task-#{@task.id}").html();

app/views/projects/index.html.haml
-# #timer{:style => "width: 100%;height:280px;background-color:lightgray;text-align:center;padding-top:10px;border-radius:10px;"}
-#   %p.pomodoro-title{:style => "font-size:1.3em;margin-bottom:0"} ---
-#   %p#time{:style => "font-size:6.5em;letter-spacing:7px;margin-bottom:7px;"} 25:00
-#   .buttons{:style => "width:140px;height:48px;margin:0 auto;position:relative;"}
-#     %span#play{:style => "cursor:pointer;visibility:visible;position:absolute;top:0;left:0;"}= fa_icon "play 3x"
-#     %span#pause{:style => "cursor:pointer;visibility:hidden;position:absolute;top:0;left:0;"}= fa_icon "pause 3x"
-#     %span#stop{:style => "cursor:pointer;position:absolute;top:0;right:0;"}= fa_icon "stop 3x"
-# #form{:style => "position:relative; margin-top: 30px;"}
-#   = form_for @project, remote: true do |f|
-#     .form-group
-#       / <haml_loud> f.label :title, &quot;New Project&quot;, style: &quot;font-size: 1.3em;&quot; </haml_loud>
-#       #project-input{:style => "position:relative;"}
-#         = f.text_field :title, class: "form-control", style: "padding-right: 225px;", placeholder: 'タスク名を入力してください'
-#         = f.label :total, "ポモドーロ数：", style: "position:absolute;top:7px;right:105px;"
-#         = f.number_field :total, class: 'form-group', value: 1, in: 1..999, style: "position:absolute;top:4px;right:50px;margin:0;text-align:center;"
-#       = f.hidden_field :status, value: 0
-#       = f.hidden_field :done, value: 0
-#     = f.submit "+", class: "btn btn-primary", style: "position:absolute; right:0; bottom:0"

app/views/users/show.html.haml
.projects{:style => "margin: 30px 0 0;"}
  %h1 プロジェクト一覧
  %ul.list-group
    - @projects.each do |project|
      %li.list-group-item
        %span.project-title
          = project.title

.pomodoros{:style => "margin: 30px 0 80px;"}
  %h1 ポモドーロ一覧
  %ul.list-group
    - @pomodoros.each do |pomodoro|
      %li.list-group-item
        %span.pomodoro-title
          = pomodoro.title